import datetime
from service_reservation_static_data import joao_data, maria_data

def create_reservation(reservation_data):
    
    # try to create the reservation
    try:        
        # add the new created ID
        # (in a real implementation, this ID would be generated by the database)
        reservation_data["id"] = 1
        return {"result":"ok", "details": {**reservation_data}}
    except Exception as e:
        return {"result":"error", "details": str(e)}

def get_reservation(reservation_id):
    
    # two possible reservations in this static service
    # (in a real implementation, this would query 
    # the database for the reservation with the given ID)
    if reservation_id == 1:
        return {"result":"ok", "details": joao_data}
    elif reservation_id == 2:
        return {"result":"ok", "details": maria_data}
    else:
        return {"result":"error", "details":f"Reservation not found, id={reservation_id}"}
    
# this is the DELETE operation, 
# but we are not really deleting the reservation, 
# just marking it as cancelled
def cancel_reservation(reservation_id, canceler_user, observation):
    
    # get the reservation to be cancelled
    result = get_reservation(reservation_id)
    if result["result"] == "error":
        return result
    
    # fill the canceler user
    reservation = result["details"]
    reservation["canceler_user"] = canceler_user
    reservation["observations"] = observation
    reservation["active"] = False

    # save the cancelled reservation
    # (in a real implementation, this would update the reservation in the database)

    # all is ok    
    return {"result":"ok", "details": f"Reservation with id={reservation_id} cancelled by {canceler_user}"}
    
def list_reservations():
    
    # (in a real implementation, this would query the database for all reservations)
    return {"result":"ok", "details": [ 
        joao_data, 
        maria_data 
        ]}

def edit_reservation(reservation_id, updated_reservation_data):
    
    # edit means: cancel the old reservation and create a new one with the new data

    # cancel the old reservation
    # the user that cancels the reservation is the same that is trying to edit it, 
    # in this static implementation
    cancel_result = cancel_reservation(reservation_id, updated_reservation_data['user'], "Reservation cancelled by an update operation")
    # if the cancellation failed, return the error
    if cancel_result["result"] == "error":
        return cancel_result

    # create a new reservation with the updated data
    create_result = create_reservation(updated_reservation_data)

    # change the ID to a new one, specific in this static implementation
    create_result["details"]["id"] = 3

    return create_result