import datetime
from service_reservation_static_data import joao_data, maria_data

def create_reservation(reservation_data):
    
    # try to create the reservation
    try:        
        # add the new created ID
        # in a real implementation, this ID would be generated by the database
        reservation_data["id"] = 1
        return {"result":"ok", "details": {**reservation_data}}
    except Exception as e:
        return {"result":"error", "details": str(e)}

def get_reservation(reservation_id):
    
    # two possible reservations in this static service
    # in a real implementation, this would query the database for the reservation with the given ID
    if reservation_id == 1:
        return {"result":"ok", "details": joao_data}
    elif reservation_id == 2:
        return {"result":"ok", "details": maria_data}
    else:
        return {"result":"error", "details":f"Reservation not found, id={reservation_id}"}
    
def cancel_reservation(reservation_id, canceler_user, observation):
    
    # two possible reservations in testing
    if reservation_id in [1, 2]:
        return {"result":"ok", "details": f"Reservation with id={reservation_id} cancelled by {canceler_user}"}
    else:
        return {"result":"error", "details":f"Reservation not found, id={reservation_id}"}
    
def list_reservations():
    
    # in a real implementation, this would query the database for all reservations
    return {"result":"ok", "details": [ 
        joao_data, 
        maria_data 
        ]}